Homework2 tasks1and2
OlgaLavrenteva/JavaHomework pull request #2
Opened 2019-03-22 19:03 UTC by OlgaLavrenteva

Fist version of tasks 1 and 2 with tests

2019-03-27 20:00 UTC, AnnaS91 requested changes
Отличная работа! Несколько замечаний и предложений в комментариях

2019-03-27 20:00 UTC, AnnaS91 commented on HW2Task1_2/src/main/java/finder/JavaKeyWordsFinderBytesIO.java
> +    static final String JAVA_KEY_WORDS = "abstract continue for new switch assert default goto package synchronized " +
а почему не public?

2019-03-27 20:00 UTC, AnnaS91 commented on HW2Task1_2/src/main/java/finder/JavaKeyWordsFinderSymbolsIO.java
> +    static final String JAVA_KEY_WORDS = "abstract continue for new switch assert default goto package synchronized " +
можно было бы переиспользовать уже объявленную строку

2019-03-27 20:00 UTC, AnnaS91 commented on HW2Task1_2/src/main/java/finder/KeyWordsFinder.java
> +        HashMap<String, Integer> matches = new HashMap<String, Integer>();
1) лучше объявлять как Map
2) в правой части можно просто прописывать <>, компилятор сам подставит нужные типы

2019-03-27 20:00 UTC, AnnaS91 commented on HW2Task1_2/src/test/java/finder/JavaKeyWordsFinderBytesIOTest.java
> +        assertTrue(expectedOutputFileContent.equals(input.toString().trim()));
а почему не assertEquals?

2019-03-27 20:00 UTC, AnnaS91 commented on HW2Task1_2/src/test/java/finder/JavaKeyWordsFinderBytesIOTest.java
> +            assertTrue(e.getMessage().equals("NotExistingFile doesn't exist."));
в тестах с ошибками чаще используют подход с Rule (пример - https://junit.org/junit4/javadoc/4.12/org/junit/rules/ExpectedException.html )

2019-03-28 08:14 UTC, OlgaLavrenteva commented on HW2Task1_2/src/main/java/finder/JavaKeyWordsFinderBytesIO.java
> +    static final String JAVA_KEY_WORDS = "abstract continue for new switch assert default goto package synchronized " +
По ошибке( Исправлю

2019-03-28 08:17 UTC, OlgaLavrenteva commented on HW2Task1_2/src/main/java/finder/KeyWordsFinder.java
> +        HashMap<String, Integer> matches = new HashMap<String, Integer>();
Это я узнала на последней лекции только, исправляю!

2019-03-28 08:20 UTC, OlgaLavrenteva commented on HW2Task1_2/src/main/java/finder/JavaKeyWordsFinderSymbolsIO.java
> +    static final String JAVA_KEY_WORDS = "abstract continue for new switch assert default goto package synchronized " +
Эту строку я осознанно продублировала, идея была в том, что JavaKeyWordsFinderSymbolsIO и JavaKeyWordsFinderBytesIO оба используют KeyWordsFinder, но друг от друга им вроде незачем зависить. Но с другой стороны, у меня они в любом случае в одном пакете, так какой тогда смысл в дубле..

2019-03-28 10:00 UTC, OlgaLavrenteva commented on HW2Task1_2/src/test/java/finder/JavaKeyWordsFinderBytesIOTest.java
> +        assertTrue(expectedOutputFileContent.equals(input.toString().trim()));
Не уловила сразу когда что лучше использовать, поправила

2019-03-28 10:00 UTC, OlgaLavrenteva commented on HW2Task1_2/src/test/java/finder/JavaKeyWordsFinderBytesIOTest.java
> +            assertTrue(e.getMessage().equals("NotExistingFile doesn't exist."));
Спасибо, переписала

2019-03-28 14:39 UTC, AnnaS91 commented on HW2Task1_2/src/test/java/finder/JavaKeyWordsFinderBytesIOTest.java
> +    @Rule
@Rule лучше объявлять в начале класса перед методами, это же поле класса

2019-03-28 14:39 UTC, AnnaS91 commented on HW2Task1_2/src/test/java/finder/JavaKeyWordsFinderBytesIOTest.java
> +        try {
можно не оборачивать в try, а thrown.expect(IOException.class) и сообщение определить до того, как вызовешь метод, бросающий эту ошибку

2019-03-28 15:44 UTC, OlgaLavrenteva commented on HW2Task1_2/src/test/java/finder/JavaKeyWordsFinderBytesIOTest.java
> +    @Rule
Перенесла в начало

2019-03-28 20:17 UTC, OlgaLavrenteva commented on HW2Task1_2/src/test/java/finder/JavaKeyWordsFinderBytesIOTest.java
> +        try {
Тоже поправила

2019-03-28 20:41 UTC, AnnaS91 approved these changes
Поменяй, пожалуйста, в тестах порядок -  в junit4 указывается вначале expected, потом actual
В остальном отличная работа, в таблице отметила

2019-03-28 20:41 UTC, AnnaS91 commented on HW2Task1_2/src/test/java/finder/JavaKeyWordsFinderBytesIOTest.java
> +        assertEquals(input.toString().trim(),expectedOutputFileContent);
в junit4 указывается вначале expected, потом actual

2019-03-28 20:41 UTC, AnnaS91 commented on HW2Task1_2/src/test/java/finder/JavaKeyWordsFinderBytesIOTest.java
> +        assertEquals(input.toString().trim(),expectedOutputFileContent);
в junit4 указывается вначале expected, потом actual

2019-03-29 09:39 UTC, AnnaS91 approved these changes

2019-03-29 12:50 UTC, merged