Homework2 task3
OlgaLavrenteva/JavaHomework pull request #3
Opened 2019-03-25 23:12 UTC by OlgaLavrenteva

2019-03-28 15:56 UTC, AnnaS91 requested changes

2019-03-28 15:56 UTC, AnnaS91 commented on HW2Task3/src/main/java/films_collection/Actor.java
> +            throw new Exception("Surname is null.");
вдогонку к последней лекции, давай поменяем на IllegalArgumentException? :)

2019-03-28 15:56 UTC, AnnaS91 commented on HW2Task3/src/main/java/films_collection/Actor.java
> +        }
лучше прямо сразу проверить someObject на null

2019-03-28 15:56 UTC, AnnaS91 commented on HW2Task3/src/main/java/films_collection/Film.java
> +        }
аналогично с null

2019-03-28 15:56 UTC, AnnaS91 commented on HW2Task3/src/main/java/films_collection/FilmsCollection.java
> +        this.films = new HashSet<>();
👍

2019-03-28 15:56 UTC, AnnaS91 commented on HW2Task3/src/test/java/films_collection/ActorTests.java
> +    public ExpectedException thrown = ExpectedException.none();
объявление перед методами

2019-03-28 15:56 UTC, AnnaS91 commented on HW2Task3/src/test/java/films_collection/FilmsCollectionTests.java
> +    @Test(expected = Exception.class)
а зачем и thrown, и expected?

2019-03-28 21:07 UTC, OlgaLavrenteva commented on HW2Task3/src/main/java/films_collection/Actor.java
> +            throw new Exception("Surname is null.");
Поменяла

2019-03-28 21:07 UTC, OlgaLavrenteva commented on HW2Task3/src/main/java/films_collection/Actor.java
> +        }
Добавила

2019-03-28 21:07 UTC, OlgaLavrenteva commented on HW2Task3/src/main/java/films_collection/Film.java
> +        }
Добавила

2019-03-28 21:08 UTC, OlgaLavrenteva commented on HW2Task3/src/test/java/films_collection/ActorTests.java
> +    public ExpectedException thrown = ExpectedException.none();
Перенесла

2019-03-28 21:08 UTC, OlgaLavrenteva commented on HW2Task3/src/test/java/films_collection/FilmsCollectionTests.java
> +    @Test(expected = Exception.class)
Мне показалось что так меньше строк и проще выглядит:( поменяла

2019-03-29 12:43 UTC, AnnaS91 approved these changes

2019-03-29 12:43 UTC, AnnaS91 commented on HW2Task3/src/test/java/films_collection/FilmTests.java
> +        assertTrue(!film1.equals(film2));
assertFalse

2019-03-29 12:53 UTC, AnnaS91 approved these changes

2019-03-29 13:37 UTC, merged